name: View CSR Contents

on:
  workflow_dispatch:
    inputs:
      csr:
        description: "CSR PEM (can be single-line)"
        required: true
        type: string

jobs:
  view-csr:
    runs-on: ubuntu-latest
    steps:
      - name: Decode CSR
        run: |
          echo "${{ github.event.inputs.csr }}" | base64 -d > request.csr

      - name: View CSR
        run: |
          openssl req -in request.csr -noout -text

